spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pos
    username: root
    password: 992412712
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    exposure:
      include: "*"
  info:
    env:
      enabled: true


